config/routes.rb
Rails.application.routes.draw do
  root 'top#index'

  get 'signup' => 'registration#new', as: :signup
  post 'signup' => 'registration#create', as: :post_signup
  get 'registration/activate' => 'registration#activate', as: :registration_activate

  get 'login' => 'session#new', as: :login
  post 'login' => 'session#create', as: :post_login
  post 'logout' => 'session#destroy', as: :logout

end

app/models/book.rb
require 'compote/normalizer'

class Book < ActiveRecord::Base
  belongs_to :publisher
  belongs_to :source

  before_validation :normalize_title

  protected
  def normalize_title
    self.title = Compote::Normalizer.normalize_book_title title
  end
end

app/models/crawled_response.rb
class CrawledResponse < ActiveRecord::Base
  include AmazonParser

  LIFETIME_SEC = 1.day

  def expired?
    return false if Rails.env.development?
    Time.now - self.updated_at > LIFETIME_SEC
  end
end

app/models/publisher.rb
require 'compote/normalizer'

class Publisher < ActiveRecord::Base
  has_many :books

  before_validation :normalize_name

  protected
  def normalize_name
    self.name = Compote::Normalizer.normalize_publisher_name name
  end
end

app/models/registration_token.rb
class RegistrationToken
  EXPIRES_IN = 1.day
  class NotFound < StandardError; end
  class InvalidToken < StandardError; end

  include ActiveModel::Model

  attr_accessor :value, :user_id
  validates_format_of :value, with: /\A[a-z0-9]{64}\z/
  validates_presence_of :user_id

  def self.create(user_id:)
    value = Digest::SHA2.hexdigest rand.to_s
    token = new value: value, user_id: user_id
    token.save!
    token
  end

  def cache_key
    self.class.cache_key value
  end

  def self.cache_key(value)
    "registration_token/#{value}"
  end

  def save!
    validate!
    Rails.cache.write cache_key, user_id, expires_in: EXPIRES_IN
  end

  def validate!
    raise InvalidToken, "token #{value.inspect} is invalid" unless valid?
  end

  def delete
    Rails.cache.delete cache_key
  end

  def self.find(value)
    user_id = Rails.cache.read cache_key(value)
    if user_id.blank?
      raise NotFound, "token #{value.inspect} not found"
    end
    token = new value: value, user_id: user_id
    token.validate!
    token
  end
end

app/models/source.rb
class Source < ActiveRecord::Base
  has_many :books

end

app/models/user.rb
require 'digest/md5'

class User < ActiveRecord::Base
  enum registration_status: { activating: 0, active: 1, leaved: 2 }
  has_secure_password
  validates_format_of :email, with: /\A\s*([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\s*\z/i
  validates_uniqueness_of :email
  validates_length_of :email, maximum: 255
  validates_length_of :password, minimum: 6, allow_blank: true
  before_validation :strip_email

  def gravatar_url(size:100)
    hash = Digest::MD5.hexdigest self.email.downcase
    "//www.gravatar.com/avatar/#{hash}.jpg?s=#{size}"
  end

  private
  def strip_email
    self.email.strip! if self.email
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user

  protected
  def login_required
    unless current_user
      redirect_to login_path
    end
  end

  private
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/registration_controller.rb
class RegistrationController < ApplicationController
  def new
    @user = User.new
  end

  def create
    user_params = params.require(:user).permit(
      :email, :password, :password_confirmation
    )
    @user = User.new(user_params)

    User.transaction do
      if @user.save
        send_activation_email @user
        session[:user_id] = @user.id
        redirect_to root_path, notice: "#{@user.email} にメールを送信しました。メールに書かれたリンクをクリックしてアカウント登録を完了してください"
      else
        render :new
      end
    end
  end

  def activate
    token = RegistrationToken.find params[:token]
    token.validate!
    @user = User.find_by_id token.user_id
    if @user.activating?
      @user.active!
      token.delete
      # FIXME
      redirect_to root_path, notice: "メールアドレス #{@user.email} の認証が完了しました"
    else
      token.delete
      render plain: 'invalid activation token', status: 404
    end
  rescue RegistrationToken::InvalidToken
    render plain: 'your activation token is invalid', status: 401
  rescue RegistrationToken::NotFound
    render plain: 'your activation token has been expired', status: 401
  end

  private
  def send_activation_email(user)
    token = RegistrationToken.create user_id: user.id
    token.save!
    url = registration_activate_url token: token.value
    logger.info "activation: #{url}"
    # TODO send mail
  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  before_action :login_required, only: [:destroy]
  def new
  end

  def create
    user = User.find_by_email(params[:email]) if params[:email]
    if user.present? && params[:password].present? && user.authenticate(params[:password])
      session[:user_id] = user.id
      # FIXME
      redirect_to root_path
    else
      flash.now.alert = 'メールアドレスまたはパスワードが間違っています'
      render :new
    end
  end

  def destroy
    session.delete :user_id
    redirect_to root_path
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/registration_helper.rb
module RegistrationHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title Compote
    meta name="viewport" content="width=device-width, initial-scale=1"
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  body role="document"
    nav.navbar.navbar-fixed-top
      .container
        .navbar-header
          .navbar-brand
            = link_to 'Compote', root_path
        #navbar.navbar-collapse.collapse
          ul.nav.navbar-nav.navbar-right
            - if current_user
              li.dropdown
                a.dropdown-toggle#account-dropdown type='button' data-toggle='dropdown' aria-haspopup='true'
                  = image_tag current_user.gravatar_url(size:20)
                  span.account-email = current_user.email
                  span.caret
                ul.dropdown-menu aria-labelledby='account-dropdown'
                  li = link_to 'アカウント情報', '#'
                  li = link_to 'ログアウト', logout_path, method: :post
            - else
              li = link_to 'アカウント登録', signup_path
              li = link_to 'ログイン', login_path

    .container role="body"
      == yield

app/views/session/new.html.slim
.page-header
  h1 ログイン

= form_tag post_login_path do |f|
  - if flash[:alert]
    #error_explanation.alert.alert-danger role="alert"
      p = flash[:alert]
  .row
    .col-xs-12.col-md-3
      p
        = label_tag :email, 'メールアドレス'
        = text_field_tag :email, '', class: 'form-control'
        br
        = label_tag :password, 'パスワード'
        = password_field_tag :password, '', class: 'form-control'
        br
      .actions = submit_tag 'ログイン', class: 'btn btn-default'

app/views/top/index.html.slim
- if flash[:notice]
  .alert.alert-info.alert-dismissible role='alert'
    button.close type='button' data-dismiss='alert' aria-label='Close'
      span &times;
    = flash[:notice]

h1 Top#index
p Find me in app/views/top/index.html.slim